### ISSUE TITLE
missing required file plivo.php

### ISSUE THREAD

**Issue by gregtampa** [plivo/plivo-examples-php#7]
all files require plivo.php which is missing.
These examples are worthless

**Comment by cachrisman** [comment]
You can get it from composer or from https://github.com/plivo/plivo-php

**Comment by gregtampa** [comment]
seen that. it requires an old version of use Guzzle\Http\Client; which is non PCI
Guzzle 3 is deprecated.

**Comment by cachrisman** [comment]
We are working on updating to the latest version of guzzle. See https://github.com/plivo/plivo-php/issues/24 for details.

**Comment by gregtampa** [comment]
found: https://github.com/plivo/plivo-php/blob/curl-init-issue/plivo.php 
Reviewed it for changes, seems this should work without guzzle. Is there any reason NOT to use this?

**Comment by cachrisman** [comment]
Check out https://github.com/plivo/plivo-php/compare/curl-init-issue...master to see all the changes. From the curl-init-issue branch to the current master, the biggest changes are composer support, the addition of the Plivo namespace and the refactor to use guzzle, so the version from curl-init-issue branch is probably safe to use. YMMV and be aware that we should have a new release with support for the latest version of guzzle soon.

**Comment by gregtampa** [comment]
Thanks, I rather use Curl. I emailed you a question also about my account.
